# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='timezone',
            field=models.CharField(default=b'UTC', max_length=40),
        ),
    ]
