# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokenizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokenizer.Token')),
            ],
        ),
    ]
