# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logbutton',
            old_name='token_id',
            new_name='token',
        ),
    ]
