# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20171003_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('initiating_button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.LogButton')),
            ],
        ),
    ]
