# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0004_logentry_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
