# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0005_auto_20171003_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbutton',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
